if(DEFINED LITEIM_UNIT_TESTS AND LITEIM_UNIT_TESTS)
    set_tests_properties(${LITEIM_UNIT_TESTS} PROPERTIES LABELS "unit")
endif()

if(DEFINED LITEIM_MYSQL_INTEGRATION_TESTS AND LITEIM_MYSQL_INTEGRATION_TESTS)
    set_tests_properties(${LITEIM_MYSQL_INTEGRATION_TESTS}
        PROPERTIES LABELS "integration;mysql;docker"
    )
endif()

if(DEFINED LITEIM_REDIS_INTEGRATION_TESTS AND LITEIM_REDIS_INTEGRATION_TESTS)
    set_tests_properties(${LITEIM_REDIS_INTEGRATION_TESTS}
        PROPERTIES LABELS "integration;redis;docker"
    )
endif()

if(DEFINED LITEIM_MYSQL_REDIS_INTEGRATION_TESTS AND LITEIM_MYSQL_REDIS_INTEGRATION_TESTS)
    set_tests_properties(${LITEIM_MYSQL_REDIS_INTEGRATION_TESTS}
        PROPERTIES LABELS "integration;mysql;redis;docker"
    )
endif()
